#!/usr/bin/env python3
"""
Slack Notification Setup Guide for HubSpot Workflows
==================================================

This guide explains how to set up Slack notifications for HubSpot workflows
to handle edge cases like "Gisela Mariotti Contadora" with no primary deals.

Author: CEO Assistant
Date: September 13, 2025
"""

def main():
    """Display the complete setup guide."""
    print("🚀 SLACK NOTIFICATION SETUP GUIDE")
    print("=" * 50)
    print()
    
    print("📋 OVERVIEW:")
    print("   This system adds Slack notifications to your existing HubSpot workflow")
    print("   to alert you when edge cases occur (like companies with no primary deals).")
    print()
    
    print("🔔 NOTIFICATION TYPES:")
    print("   🚨 WARNING: No primary deals found (like Gisela Mariotti)")
    print("   ℹ️  INFO: No won deals found")
    print("   ✅ SUCCESS: Field updated successfully")
    print("   ❌ ERROR: Workflow execution failed")
    print()
    
    print("⚙️  STEP 1: CREATE SLACK WEBHOOK")
    print("-" * 40)
    print("1. Go to your Slack workspace")
    print("2. Navigate to: Apps → Incoming Webhooks")
    print("3. Click 'Add to Slack'")
    print("4. Choose the channel where you want notifications")
    print("5. Copy the webhook URL (starts with https://hooks.slack.com/)")
    print()
    
    print("⚙️  STEP 2: CONFIGURE HUBSPOT ENVIRONMENT")
    print("-" * 40)
    print("1. Go to HubSpot → Settings → Integrations → Custom Code")
    print("2. Find your workflow's custom code")
    print("3. Add environment variable:")
    print("   Name: SLACK_WEBHOOK_URL")
    print("   Value: [Your webhook URL from Step 1]")
    print()
    
    print("⚙️  STEP 3: UPDATE CUSTOM CODE")
    print("-" * 40)
    print("1. Replace your existing custom code with the enhanced version")
    print("2. The enhanced code includes:")
    print("   ✅ All existing functionality")
    print("   ✅ Slack notification logic")
    print("   ✅ Enhanced error handling")
    print("   ✅ Edge case detection")
    print()
    
    print("⚙️  STEP 4: TEST THE SYSTEM")
    print("-" * 40)
    print("1. Run the workflow on 'Gisela Mariotti Contadora'")
    print("2. You should receive a Slack notification like:")
    print()
    print("   ⚠️ No Primary Deals Found")
    print("   Company: Gisela Mariotti Contadora")
    print("   Company ID: 9019067673")
    print("   Message: Company has 5 deals but NO PRIMARY associations.")
    print("   Deal Details:")
    print("   • 13451 - Global Energy Group (G.E.G.) S.A. (closedwon) - 2017-06-04")
    print("   • 62549 - FATEA LATINOAMERICANA S.A. (closedwon) - 2022-04-22")
    print("   • 94105 - FARADAY S A I C F (closedwon) - 2025-06-27")
    print("   • 94127 - Altatension S.A. (closedwon) - 2025-06-30")
    print("   • 96266 - Glamex S.A. (closedwon) - 2025-08-22")
    print()
    
    print("🎯 WORKFLOW DECISION BRANCHING")
    print("-" * 40)
    print("The enhanced workflow now includes decision logic:")
    print()
    print("IF primaryDealIds.length === 0:")
    print("  → Send WARNING notification to Slack")
    print("  → Log edge case")
    print("  → Skip field update")
    print()
    print("ELSE IF wonDates.length === 0:")
    print("  → Send INFO notification to Slack")
    print("  → Log info")
    print("  → Skip field update")
    print()
    print("ELSE IF needsUpdate:")
    print("  → Update field")
    print("  → Send SUCCESS notification to Slack")
    print()
    print("ELSE:")
    print("  → No notification needed")
    print("  → Field already correct")
    print()
    
    print("🔧 ALTERNATIVE APPROACHES")
    print("-" * 40)
    print("If you prefer separate workflows:")
    print()
    print("Option A: Separate Slack Workflow")
    print("1. Create a new workflow triggered by 'Company property changes'")
    print("2. Filter: first_deal_closed_won_date = NULL")
    print("3. Add Slack action step")
    print("4. This would notify when field is cleared")
    print()
    print("Option B: HubSpot Native Slack Integration")
    print("1. Install HubSpot Slack app")
    print("2. Use 'Send Slack message' action in workflow")
    print("3. Simpler but less customizable")
    print()
    
    print("📊 MONITORING AND ANALYTICS")
    print("-" * 40)
    print("Track these metrics in Slack:")
    print("• Number of 'No Primary Deals' warnings per day")
    print("• Number of successful field updates")
    print("• Number of workflow errors")
    print("• Companies requiring manual intervention")
    print()
    
    print("🚨 TROUBLESHOOTING")
    print("-" * 40)
    print("If Slack notifications don't work:")
    print("1. Check webhook URL is correct")
    print("2. Verify SLACK_WEBHOOK_URL environment variable")
    print("3. Check Slack channel permissions")
    print("4. Review HubSpot workflow logs for errors")
    print()
    
    print("✅ BENEFITS")
    print("-" * 40)
    print("• Proactive monitoring of edge cases")
    print("• Immediate notification of data quality issues")
    print("• Better visibility into workflow performance")
    print("• Faster resolution of association problems")
    print("• Improved data accuracy and reliability")
    print()
    
    print("🎯 NEXT STEPS")
    print("-" * 40)
    print("1. Set up Slack webhook")
    print("2. Add environment variable to HubSpot")
    print("3. Update custom code")
    print("4. Test with Gisela Mariotti Contadora")
    print("5. Monitor notifications and refine as needed")

if __name__ == "__main__":
    main()
