import { devDayBriefInstructions } from './devday-theme.mjs';

// This file contains creative briefs, not executable page modules or fixtures.
// prepare-demo submits each brief through the ordinary authenticated builder.
export const demoPreparationVersion = 'generated-personas-devday-2026-v1';

const shared = `Create my complete personal page through the normal builder. Design the entire canvas, artwork, forms and states in generated source. ${devDayBriefInstructions} Keep it distinctive, concise, responsive and accessible, with generous space and a strong visual centerpiece. Use inline SVG/CSS. Preserve all existing tiles, project IDs, capabilities, contributions and extras exactly. Include meaningful tests. Do not show implementation details or long explanatory essays to visitors.`;

const healthCapability = `For working AI answers declare meta.capabilities=['health-chat']. You own ALL its UI and styling. Include <section data-service="health-chat"> with a normal form, a textarea name="message", and a submit button. Include a data-service-messages container and <template data-service-message><article><span data-field="role" data-role-user="You" data-role-assistant="AI health guide"></span><p data-field="content"></p></article></template>, styled as a beautiful conversation. Include data-service-sources plus <template data-service-source><a data-field="url"><span data-field="title"></span></a></template>. Include data-service-note and data-service-error text targets, authored copy marked data-service-status="loading", and type=button controls with data-service-operation="cancel" and "clear". Optional clickable sample questions use data-service-operation="submit" with data-service-input JSON containing message. The trusted bridge streams and fills these slots; never fake an answer in reduce. Keep the textarea and send button easy to find. Clearly identify AI general health education, not diagnosis or emergency care. Invite general questions without personal details; conversation is separate from public space state. Do not add diagnosis, prescriptions or unsupported clinical claims.`;

const spaceAgentCapability = `Connect a REAL AI through meta.capabilities=['space-agent'] and meta.agent. Render its designed UI inside <section data-service="space-agent">: native form WITHOUT data-action, textarea name="message" maxlength="1200", submit button, data-service-messages container, <template data-service-message><article><small data-field="role" data-role-user="You" data-role-assistant="AI companion"></small><p data-field="content"></p></article></template>, data-service-error and data-service-note. Include a hidden data-service-status="loading" slot and type=button data-service-operation="cancel". Put ALL ordinary data-action game/painting controls OUTSIDE the service section. Never substitute keyword matching or canned replies for AI. Keep the input prominent and conversation compact; identify it as AI.`;

export const demoPrompts = Object.freeze([
  Object.freeze({ id: 'mira', name: 'Mira', requiredCapabilities: [], prompt: `${shared}

I am Mira, a curious botany lover. Make my space an exquisite living herbarium: a black herbarium with vivid green botanical linework, violet evening light, crisp sans-serif labels and delicate, slowly unfurling plant illustrations. It should feel optimistic and quietly futuristic, not like a dashboard. Give visitors a delightful Spring / Summer / Evening light control with a real saved per-person setting. Present my botanical projects as beautiful illustrated tiles, dynamically rendering every existing project so adding another is natural. If there are no projects, declare three in meta.projects: Fern studies, Moon garden and Herbarium. Existing project IDs and votes must survive. Each person gets three total support points across projects, with +Grow and remove controls, clear remaining points, and real host-validated behavior. Keep controls small and the plants expressive. Preserve my current catalog entries even if there are already more than three. Rebuild the page coherently around the botanical theme; it must all be ordinary generated canvas code.` }),
  Object.freeze({ id: 'james', name: 'James', requiredCapabilities: [], prompt: `${shared}

I am James, a finance professional who values clarity and a long-term view. Create a sophisticated personal finance observatory on black with charcoal surfaces, white numbers, vivid green trajectories and restrained violet comparisons. Use large clear numbers, fine graph lines and a refined editorial composition. Build a useful interactive compounding scenario with starting amount, monthly contribution, years and assumed annual rate. A real form saves only the acting visitor's scenario; draw a clear inline SVG trajectory and show contributions versus illustrative future value. Validate numeric ranges and make the assumptions visible. Label it an illustration, not a forecast or investment advice. Balance this console with a concise prepopulated Learning desk containing three static educational cards: Compounding explains that returns can themselves earn returns over time and that actual returns vary; Inflation explains that rising prices reduce the purchasing power of a fixed amount of money; Diversification explains that spreading investments across different holdings can reduce concentration risk but cannot eliminate losses. Label this section Educational demo content. Keep all card content in the generated source, visible immediately without loading or a network request. Avoid fake tickers, performance claims, fabricated prices, current-rate claims and excessive text.

Do not declare the finance-news capability or include any data-service="finance-news", data-service-auto, or data-service-operation="refresh" bindings. Remove the live feed and its refresh control if editing an existing page. This page's calculator and learning cards must work without any external service.` }),
  Object.freeze({ id: 'jake', name: 'Jake', requiredCapabilities: ['health-chat'], prompt: `${shared}

I am Jake, a female nurse. Create a compassionate, modern care room on black and charcoal, with clear white type, soft green breathing rings and restrained violet accents. The centerpiece is a beautiful, immediately usable AI health conversation, with a calm visual motif inspired by breathing and a welcoming short introduction. Keep the question field and send control visible without needing to hunt below decorative content. Add just a few general sample questions such as 'Why does sleep matter?' and 'How can I prepare for a medical appointment?' Use concise readable messages, a refined loading animation, source chips, and thoughtful empty and error states. You may add a small working appointment-preparation disclosure, but the conversation is the focus. Respect the general-education scope and do not imitate a human clinician's signed reply.

${healthCapability}` }),
  Object.freeze({ id: 'erica', name: 'Erica', requiredCapabilities: [], prompt: `${shared}

I am Erica, a neuroscientist who studies learning and connection. Create a luminous neuroscience field notebook: a black field with luminous violet and green signals, a beautiful animated inline SVG neural network, and clear system sans-serif typography. Make a working Attention / Memory / Movement explorer with an actor-owned saved selection, visible changes in the conceptual network and a concise corresponding fact. Safe educational facts: frontal lobes help complex thinking, learning and problem-solving (NIH/NIMH Get to Know Your Brain); the hippocampus is essential for forming memories (NIH/NINDS Dementias); the cerebellum helps coordinate movement and balance (NIH/NIMH Get to Know Your Brain). Attribute these source names briefly without inventing citations. Label the visual as a conceptual network, not an anatomical scan. Add a short personal note about curiosity, memory and neural plasticity, clearly fictional demo research interests, with no fabricated publications or credentials. Make exploration feel tactile and surprising while staying calm and accessible.` }),
  Object.freeze({ id: 'iris', name: 'Iris', requiredCapabilities: ['space-agent'], requiredAgentActions: ['paint_pixels', 'fill_canvas', 'paint_shapes', 'flood_fill'], prompt: `Build an OpenAI DevDay 2026 canvas module: black/charcoal, white system sans-serif, green #04b84c/violet #924ff7 accents. Preserve records, escape user strings, include meaningful tests and accessible responsive controls.

I am Iris, a painter. Title "The shared canvas." at36px, small "Iris / painter" label, no hero prose. Art is the centerpiece: pure-white48x32 canvas, no grid lines, subtle1px border, padding16px. Desktop: minmax(0,1fr) canvas plus200px tools,24px gap; tools above on narrow screens. Keep words minimal.

Use ONE native <canvas data-key="painting" tabindex="0" aria-label="Shared painting"> outside service sections, not per-pixel buttons. data-paint-grid JSON: {action:'paint_pixels',columns:WIDTH,rows:HEIGHT,color:SELECTED_INDEX,colorValue:SELECTED_HEX,palette:PALETTE,background:'#ffffff'}. data-paint-pixels is exactly WIDTH*HEIGHT row-major characters: '.' blank, '0123456789abcdefghijklmnopqrstuv' palette indexes. CSS width:100%;height:auto;aspect-ratio:WIDTH/HEIGHT;display:block;touch-action:none;user-select:none. Host renders and handles pointer/keyboard; no browser scripts. Caption "Drag to paint · Arrows + Space". Derive dimensions once for render/reducer/agent, axes1..256, max65536 pixels. Doubling means both axes48x32→96x64→192x128 on the same displayed surface. New canvas blank; preserve old art.

Eight circular palette buttons, fixed32px square, flex:0 0 32px, padding0, border-radius50%, selected outline, accessible names, wrapping row. Preserve palette-index meanings; new palette #006aff,#ff8549,#ffdf57,#04b84c,#222222,#924ff7,#72c7ff,#ffffff. Clear my marks removes only visitor-owned layers.

Preserve legacy extras.canvas records {actorId,color,marks:{cell:[paletteIndex,sequence]}} as48x32 layers. New layers compact, versioned, actor-owned, with explicit dimensions; latest sequence wins. Render/resample each layer from its own dimensions; never reinterpret old indexes or rewrite others' records. Keep unrelated data. Use compact runs for uniform fills; obey host500000-character state bound. Set meta.agent.paintContext={canvasKey:'painting',namespace:'canvas'} for authoritative visible pixels, not history. Never persist that projection.

Declare matching bounded meta.agent schemas and reducers for paint_pixels({columns,rows,cells:[{cell,color}]}) with1..120 cells, fill_canvas({columns,rows,color}), flood_fill({columns,rows,x,y,color}), and paint_shapes({columns,rows,shapes:[{kind:'rect'|'ellipse'|'line',x1,y1,x2,y2,color,filled,width}]}). Integer coordinates, inclusive endpoints,1..32 shapes, stroke width1..32. Validate everything before mutation; reject stale dimensions, invalid cells/colors and excessive work. Deterministic whole-canvas fill takes ONE action even at256x256; connected fill stops at different visible colors. Shape batches support filled/outlined rectangles, ellipses and lines. Agent: choose bulk tools for coverage, pixels for detail; whole repaint includes old art via own overlay, background-only preserves foreground. Plan composition within action budget, check refreshed visible result, stop when satisfied, honestly report unfinished work.

Compact Paint with words sidebar: <section data-service="space-agent"> with form WITHOUT data-action, single-line input name="message" maxlength1200 aria-label="Describe what to paint" placeholder="A little wildflower…", submit Paint, type=button data-service-operation="cancel" Stop. Enter submits. Include hidden data-service-messages and <template data-service-message><p data-field="content"></p></template>, visible data-service-text/data-service-error, hidden data-service-note/data-service-status="loading". Show brief truthful final result, not transcript or silent completion.

Tests: exact full coverage at maximum resolution; shape/fill boundaries, atomic rejection and stale dimensions; preserved other/legacy layers, overlap/clear; repeated resolution increases; exact raster count and service bindings.` }),
  Object.freeze({ id: 'luca', name: 'Luca', requiredCapabilities: ['space-agent'], prompt: `${shared}

I am Luca, a language teacher. Build "Little by little", a delightful gamified Spanish practice space. Create a welcoming illustrated night-time travel notebook: black/charcoal, white system sans-serif headings, green and violet accents, simple geometric inline SVG café/city illustrations with sparing orange lights. Discreet "Luca / language teacher" identity. Lead with "Your next adventure starts with a word." Give the page one clear interactive challenge, a beautiful small illustrated path with three stops (Hello, Café, Around town), a restrained XP badge/progress indicator, and a live "Meet me at the café" AI conversation area. Avoid dashboard clutter, walls of copy, fake streaks, timers or audio controls.

Create six short, correct beginner Spanish multiple-choice questions, two per stop. Use familiar phrases like hola, buenos días, gracias, un café por favor, la estación and ¿dónde está…? Include accents and concise English explanations. Present one question at a time with three big answer buttons. Wrong answers give gentle feedback and can retry; correct answers give a small satisfying CSS celebration and a Continue button. Store progress only in extras.learning[actor.id]={actorId,...}. Validate question and choice IDs against source-defined lessons. Derive XP as 10 per unique correctly solved question, cap at 60, never accept client-supplied correctness/XP. Repeating an answer must not farm XP. Keep other people's progress untouched. Make the completed state joyful and allow revisiting lessons without losing earned XP. Label saved progress as visible in this shared space; don't ask for private learner details. Test wrong answer, correct answer, duplicate reward refusal, invalid choice and another learner's preserved progress.

meta.agent.actions=[]: this is a real conversational AI tutor, separate from scored lesson progress. Its instructions: act as a warm beginner Spanish café partner; start easy; use short Spanish with brief English support; ask one question at a time; correct gently with natural phrasing; respond to arbitrary learner sentences; never claim to award game XP, modify progress, or be the human Luca. No fake chat transcript. A tiny prompt cue can suggest "Hola, un café por favor".

${spaceAgentCapability}` }),
  Object.freeze({ id: 'karen', name: 'Karen', requiredCapabilities: [], requiredGames: ['pacman', 'space-invaders', 'snake', 'tetris'], prompt: `${shared}

I am Karen, an arcade enthusiast. Create my complete four-game arcade, with exactly four prominent playable game tiles titled PacMan, Space Invaders, Snake, and Tetris. Give the entire space a cohesive retro arcade atmosphere: black cabinets, charcoal surfaces, white system sans-serif labels, vivid green and violet accents with blue/orange game details, crisp pixel art, restrained cabinet trim, compact score displays and an inviting "One more game" heading. Use a responsive two-by-two desktop layout and a single column on phones. Keep every playfield, score and control legible. Each tile should look like its own little cabinet within the same arcade. Avoid excessive flashing and honor reduced motion.

These must be real playable continuous games, not decorative previews, links, turn-based imitations, or animations without gameplay. Use the supported sandboxed game runtime with meta.games IDs pacman, space-invaders, snake, and tetris, four exported game modules, distinct checkpoint actions and four matching data-game sections. All four games must coexist independently on the same page. Preserve each visitor's progress in their own actor-owned records; starting or restarting one game must not reset the others. Provide visible Start, Pause/Resume and New game controls and clear compact instructions. Include touch direction/action buttons and scoped keyboard bindings, so buttons, keyboard and Live voice operate the same game controls. Start paused until the visitor presses Play; never capture page-wide keys while someone is typing.

PacMan: a readable maze with pellets, walls, a moving yellow character and chasing ghosts, directional steering, collision, score, lives and win/game-over states. Space Invaders: descending rows of moving aliens, a player ship that moves left/right and shoots, visible projectiles, collisions, score and win/game-over states. Snake: continuous grid movement, growing body, food spawning only on empty cells, directional steering, score and wall/self-collision game over. Tetris: falling tetrominoes, left/right movement, rotation, soft and hard drop, settled pieces, complete-line clearing, score and game over. Use fair, approachable speeds. Use bounded deterministic simulation and sandbox drawing commands, with no browser scripts, network assets, imports or external game embeds. Meaningful tests must exercise each game's actual progression, collisions or line clearing, restart, and saved-progress isolation. The result should be instantly understandable and genuinely enjoyable to play.` }),
]);
