// One creative contract for generated pages, prepared worlds and their icons.
// These instructions guide model output; they do not grant runtime privileges.
export const DEV_DAY_THEME_VERSION = 'openai-devday-2026-v1';

export const devDayDesignInstructions = `OPENAI DEVDAY 2026 CREATIVE CONTRACT
Every new world, tile, control, illustration and later edit belongs to the same Little Worlds at OpenAI DevDay experience. Apply this contract to the generated canvas itself, not just the surrounding host. Keep each person's subject, personality, useful content and spatial composition distinctive; do not give every world the same dashboard or replace its artwork with generic event logos.

THEME PRIORITY: The owner's explicit theme request takes priority over the defaults below, on both first creation and later edits. A page/world theme request such as "make the theme light" means restyle the entire generated page, not merely turn an illustration from night to day. Only limit a change to an illustration or tile when the owner scopes it that way. For a first build with no specified theme, you MUST use the app appearance supplied for this request. For an existing world with no requested theme change, preserve its authored palette even if the surrounding app's mode has changed. Never silently reset a custom theme during an unrelated edit.

Default dark palette: black #000000 canvas, charcoal #111111 surfaces, white #ffffff primary text, neutral #a3a3a3 secondary text, and fine #2a2a2a boundaries. Default light palette: pale neutral #f7f8fa canvas, white #ffffff surfaces, near-black #202630 primary text, slate #596273 secondary text, and fine #d9dee7 boundaries. Event accents are green #04b84c and purple #924ff7, with blue #006aff and orange #ff8549 used sparingly for meaning or contrast. On light surfaces use darker green #008535 and purple #7134bd for readable small accent text. Use black labels on bright green buttons and readable contrast for text, errors, selected and disabled states. Do not encode information by color alone. Keep the default design crisp and geometric; a custom theme requested by the owner may change these defaults.

When changing the page theme, update every authored surface and its foreground together: document/body and outer wrappers, hero, cards, navigation within the world, forms, buttons, borders, captions, chart chrome, disclosures and all hover/focus/selected/disabled/loading/error states. Remove or override stale hardcoded colors, gradients and shadows that would keep the old palette visible. Set the generated document's color-scheme to match its chosen theme. Prefer a small coherent set of CSS color tokens used throughout. Do not simulate a light theme with opacity, a washed-out overlay or a blanket invert/filter; preserve meaningful image, artwork and game colors. Before submitting the patch, check that the root canvas and ordinary tiles visibly use the requested palette, with readable text and controls throughout.

The trusted frame has dark fallback styles. In your generated <style>, set :root color-scheme and override --devday-background, --devday-surface, --devday-text, --devday-muted and --devday-line to the chosen page palette so inherited defaults and uncovered canvas match too. Your authored CSS loads after those fallbacks; no browser script is needed.

Typography is system sans-serif with Arial/sans-serif fallback, or inherit the trusted frame font. Use regular/medium weights, clear spacious headings, readable labels and restrained tracking; no downloaded fonts, imports or external resources. The world is demonstrated on a booth TV as well as used on a laptop: the subject, current result and next action must be understandable from a few steps away. On a full-width desktop canvas, aim for 22–24px body text and controls, 18px supporting labels, and a clear 40–80px heading hierarchy; scale up naturally on larger canvases. In a narrow comparison pane or phone, keep body text and controls at least 18px and supporting labels at least 15px where practical. These are responsive design targets, not rigid dimensions or a reason to override an owner's explicit compact layout. Use fluid type such as clamp(18px,1.5vw,32px), reflow columns before shrinking essential text, and let controls grow with their labels. Avoid 9–12px instructions, tiny chart legends, and large empty margins around a narrow fixed-width page. Keep reading lines comfortable, concise visible labels and strong foreground/background contrast; let the artwork fill the remaining space without burying controls below a decorative hero. At both narrow and wide widths, account for longer real content without clipping, overlap or horizontal page scrolling. Prefer thin borders, crisp geometry, generous negative space and small corner radii. Brackets, coordinate lines, orbital dots and small geometric details may echo the event identity without overwhelming the actual experience. Do not duplicate host navigation or attach an OpenAI logo to fictional personal content.

For groups of peer tiles, default to a balanced responsive grid unless the owner requests asymmetry, masonry or a featured hierarchy. Use equal-width columns (for example repeat(2, minmax(0, 1fr)) when two columns fit), consistent gaps and stretch tiles to equal height within each row so their top and bottom edges align. Give comparable artwork areas consistent proportions, align heading/content starts, and use internal grid/flex rows to align bottom controls despite differing text lengths. Let rows grow for longer content and expanded disclosures; do not crop content or force brittle fixed heights. Use min-width:0 and responsive single-column stacking on narrow screens. Adding or editing a tile should preserve the group's shared alignment and spacing. Never fill an incomplete row with unsolicited dummy tiles or discard existing content just to create symmetry.

Apply the theme to every visual state: introductory art, tiles, forms, charts, help, empty/loading/error/completed states, selection, keyboard focus and game controls. Motion should be fluid, purposeful and efficiently rendered: a brief opacity/transform entrance, responsive hover/focus feedback, and continuous orbital or signal motion where it fits the subject. Keep ambitious requested artwork and animation visually rich while choosing a representation that sustains smooth display-refresh-paced movement. Restrained motion means deliberate amplitude and pacing, not sparse frames or jerky pose changes. Avoid flashing, busy neon effects and unnecessary redraw work. Honor prefers-reduced-motion by disabling decorative motion; preserve game mechanics, explicit Start/Pause controls, intentional pacing and responsive input.

Keep functional colors where they carry necessary meaning: a painter's blank canvas remains white, existing drawings retain their palette-index meaning, and games retain distinguishable pieces, pellets, hazards and players. An owner's specific artwork request may introduce other colors inside that artwork. The surrounding page, controls and new tiles follow the chosen page theme, which may be light, dark or custom. Never recolor stored artwork or reinterpret existing palette indexes merely to match the page.

For edits and restyling, retain every existing tile title and stable project ID, current catalog entry, service and agent capability, action name/schema, game ID/export, control, simulation rule, drawing behavior and actor-owned record unless the owner explicitly requests a functional change. Preserve saved contributions, progress, drawings, messages and all unrelated extras. Derive new visuals from existing live data instead of replacing it with demo data. Keep an existing embedded agent's actions working and make its instructions aware of the theme when it creates visible artwork or content. Reuse passing behavioral tests for visual-only changes; add checks for any new behavior.`;

export const devDayBriefInstructions = 'Use OpenAI DevDay 2026: system sans-serif, #04b84c green/#924ff7 purple accents, geometric art, fluid motion and reduced-motion support. For TV/laptop legibility use 22–24px desktop text/controls, readable labels and reflow before shrinking. Owner themes override defaults; first builds follow app mode, edits retain the authored palette. Align peer tiles with equal rows and consistent gaps unless requested otherwise. Preserve saved content and behavior.';

// Only a validated app preference and a host-derived blank-canvas flag enter
// this instruction. They describe defaults, never override an owner's request.
export function buildAppearanceInstructions({ appTheme = 'dark', firstBuild = false } = {}) {
  if (!['light', 'dark'].includes(appTheme)) throw new TypeError('appTheme must be light or dark.');
  return `CURRENT BUILD APPEARANCE\nApp appearance for this request: ${appTheme}.\nCanvas state: ${firstBuild ? 'first build' : 'existing world'}.\n${firstBuild
    ? `If the owner has not specified a theme, create the entire page using the default ${appTheme} palette above. The blank seed's colors are not an existing authored theme.`
    : 'Preserve the existing world palette unless the owner requests a theme change. The app appearance alone is not a restyle request.'}\nAn explicit owner theme overrides these defaults and must be applied across the whole generated page unless the owner specifies a narrower scope.`;
}

export const devDayAgentInstructions = `For visual contributions you create in this OpenAI DevDay 2026 world, favor crisp geometric forms, clear negative space and the event palette: green #04b84c, purple #924ff7, blue #006aff and orange #ff8549, with black/charcoal and white. This is the default art direction even if an older space description mentions a previous style. Honor the visitor's specific subject and requested artwork colors. Use only the palette values or indexes actually documented by the current space and allowed by its tools; never invent a palette entry, change an index's meaning or recolor existing marks to force the theme. If an exact event color is unavailable, choose an appropriate allowed color. Preserve existing work, white blank painting areas, and all actor ownership rules. This art direction grants no additional actions or source-editing permissions. For nonvisual conversations, follow the space's subject naturally without inserting event branding into every reply.`;

export const devDayIconInstructions = `Create an icon for the OpenAI DevDay 2026 Little Worlds collection. Use a deep black #000000 or charcoal #111111 background, a crisp dimensional geometric object with vivid green #04b84c and purple #924ff7 accents, small white highlights, and only sparse blue #006aff or orange #ff8549 where the subject needs them. Keep the published world's recognizable subject and personality, including its existing subject when restyling a reference image; vary the object across worlds instead of using the same event symbol. The style is refined, tactile, simple and luminous, with controlled soft lighting and clean edges. Avoid pastel backgrounds, cream-paper styling, busy neon, a dashboard screenshot or a generic glowing orb. Center one clear composition with a generous dark safe margin so it remains legible at 32px and in a circular crop. No text, letters, numbers, logos, wordmarks, borders or watermarks.`;
