const API='https://cguutkghsnhmwzghkmnc.supabase.co/functions/v1/aumara-staff-api';
const LS={device:'aumara.pwa.device',refresh:'aumara.pwa.refresh',user:'aumara.pwa.user',dashboard:'aumara.pwa.dashboard',team:'aumara.pwa.team',finance:'aumara.pwa.finance',tasks:'aumara.pwa.tasks',queue:'aumara.pwa.queue',loginOptions:'aumara.pwa.loginOptions',lastSync:'aumara.pwa.lastSync'};
const state={token:'',user:null,dashboard:null,team:null,finance:null,tasks:null,active:'home',busy:false,loginOptions:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=v=>Number(v||0); const hours=v=>num(v).toLocaleString('ru-RU',{maximumFractionDigits:2}); const eur=v=>num(v).toLocaleString('ru-RU',{style:'currency',currency:'EUR'});
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Madrid'});
const addDays=(d,n)=>{const x=new Date(d+'T12:00:00Z');x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10)};
const uuid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
function get(k,f=null){try{const v=localStorage.getItem(k);return v==null?f:JSON.parse(v)}catch{return f}}
function put(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
function del(k){try{localStorage.removeItem(k)}catch{}}
function ctx(){return {userAgent:navigator.userAgent,platform:navigator.platform||'',language:navigator.language||'',timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone||'Europe/Madrid',standalone:matchMedia('(display-mode: standalone)').matches||navigator.standalone===true,origin:location.origin,pwaVersion:'2.1.0'}}
async function rpc(fn,args=[]){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({fn,args})});const j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.error||`HTTP ${r.status}`);return j.result}
function toast(msg,type=''){const n=$('#toast');n.textContent=msg;n.className='toast '+type;n.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.add('hidden'),3500)}
function net(){const n=$('#net');const online=navigator.onLine;n.textContent=online?'В сети':'Офлайн';n.className='pill '+(online?'online':'offline');$('#syncNow').disabled=!online}
function lastSync(){const v=get(LS.lastSync,'');$('#lastSync').textContent=v?`синхр. ${v}`:'локальный режим'}
function saveSnapshot(key,data){put(key,{savedAt:new Date().toISOString(),data});put(LS.lastSync,new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'}));lastSync()}
function loadSnapshot(key){return get(key)?.data||null}
function queue(){return get(LS.queue,[])||[]}
function setQueue(q){put(LS.queue,q);renderQueue()}
function renderQueue(){const q=queue();const n=$('#queuebar');if(q.length){n.textContent=`Ожидают синхронизации: ${q.length}`;n.classList.remove('hidden')}else n.classList.add('hidden')}
function setAuthed(on){$('#login').classList.toggle('hidden',on);$('#app').classList.toggle('hidden',!on);if(on)renderAll()}
async function loadLoginOptions(){let cached=get(LS.loginOptions);if(cached){state.loginOptions=cached;renderLoginOptions()}if(!navigator.onLine)return;try{const v=await rpc('getLoginOptions',[]);state.loginOptions=v;put(LS.loginOptions,v);renderLoginOptions()}catch(e){if(!cached)toast(e.message,'error')}}
function renderLoginOptions(){const sel=$('#staffId');const users=state.loginOptions?.users||[];const current=sel.value;sel.innerHTML='<option value="">Выберите сотрудника</option>'+users.map(u=>`<option value="${esc(u.staffId)}">${esc(u.name)}</option>`).join('');if(users.some(u=>u.staffId===current))sel.value=current}
async function login(){if(!navigator.onLine)return toast('Для первого входа нужен интернет','warn');const staffId=$('#staffId').value,pin=$('#pin').value.trim();if(!staffId||!pin)return toast('Выберите сотрудника и введите PIN','warn');let device=get(LS.device);if(!device){device=uuid();put(LS.device,device)};$('#loginBtn').disabled=true;try{const r=await rpc('loginDevice',[staffId,pin,{deviceId:device,label:`AUMARA PWA ${navigator.platform||'device'}`},ctx()]);state.token=r.token;state.user=r.user;put(LS.refresh,r.refreshToken);put(LS.user,r.user);$('#pin').value='';setAuthed(true);await syncAll(true);toast('Устройство закреплено','')}catch(e){toast(e.message,'error')}finally{$('#loginBtn').disabled=false}}
async function resume(){const device=get(LS.device),refresh=get(LS.refresh);state.user=get(LS.user);state.dashboard=loadSnapshot(LS.dashboard);state.team=loadSnapshot(LS.team);state.finance=loadSnapshot(LS.finance);state.tasks=loadSnapshot(LS.tasks);if(state.user)setAuthed(true);if(!device||!refresh){setAuthed(false);return false}if(!navigator.onLine){setAuthed(!!state.user);return !!state.user}try{const r=await rpc('resumeDeviceSession',[device,refresh,ctx()]);state.token=r.token;state.user=r.user;put(LS.user,r.user);setAuthed(true);return true}catch(e){state.token='';if(!state.user)setAuthed(false);toast('Нужен один вход по PIN на этом устройстве','warn');return false}}
function logout(){['refresh','user','dashboard','team','finance','tasks'].forEach(k=>del(LS[k]||k));del(LS.refresh);del(LS.user);state.token='';state.user=null;setAuthed(false);toast('Локальная сессия очищена')}
async function ensureToken(){if(state.token)return true;return resume()}
async function syncAll(force=false){if(!navigator.onLine)return renderAll();if(!(await ensureToken()))return;$('#syncLabel').textContent='синхронизация…';try{state.dashboard=await rpc('getDashboard',[state.token]);saveSnapshot(LS.dashboard,state.dashboard);if(state.user?.isOwner){const [team,fin,tasks]=await Promise.all([rpc('v200GetOwnerTeam',[state.token,{}]),rpc('v200GetOwnerFinance',[state.token,financePeriod()]),rpc('v19GetTaskBoard',[state.token,{}])]);state.team=team;state.finance=fin;state.tasks=tasks;saveSnapshot(LS.team,team);saveSnapshot(LS.finance,fin);saveSnapshot(LS.tasks,tasks)}else{state.tasks=await rpc('v19GetTaskBoard',[state.token,{}]);saveSnapshot(LS.tasks,state.tasks)}await flushQueue();renderAll()}catch(e){toast(`Синхронизация: ${e.message}`,'error')}finally{$('#syncLabel').textContent='';lastSync()}}
function financePeriod(){return {fromDate:$('#fromDate')?.value||addDays(today(),-30),toDate:$('#toDate')?.value||today()}}
async function loadFinance(){if(!state.user?.isOwner)return;if(!navigator.onLine)return renderFinance();if(!(await ensureToken()))return;try{state.finance=await rpc('v200GetOwnerFinance',[state.token,financePeriod()]);saveSnapshot(LS.finance,state.finance);renderFinance()}catch(e){toast(e.message,'error')}}
function showTab(name){state.active=name;$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.section').forEach(s=>s.classList.add('hidden'));$('#sec-'+name).classList.remove('hidden');if(name==='finance')renderFinance();if(name==='team')renderTeam();if(name==='tasks')renderTasks();if(name==='home')renderHome()}
function renderAll(){if(!state.user)return;$('#who').textContent=state.user.name||'';$('#version').textContent='PWA 2.1';$('#ownerTabs').classList.toggle('hidden',!state.user.isOwner);renderHome();renderTeam();renderFinance();renderTasks();showTab(state.active);renderQueue();net();lastSync()}
function renderHome(){const d=state.dashboard;const root=$('#homeBody');if(!d){root.innerHTML='<div class="empty">Нет сохранённого среза. Подключитесь к интернету один раз.</div>';return}const c=d.clock||{};const shifts=d.todayShifts||[];root.innerHTML=`<div class="clock-card"><div class="muted small">Сегодня ${esc(d.today||today())}</div><div class="clock-state">${c.status==='WORKING'?'На смене':c.status==='BREAK'?'Перерыв':'Не на смене'}</div><div class="muted">${c.startedAt?`Начало: ${esc(String(c.startedAt))}`:'Готово к началу смены'}</div><div class="clock-buttons">${c.status==='OFF'?'<button class="btn" data-clock="START">Начать смену</button>':c.status==='WORKING'?'<button class="btn alt" data-clock="BREAK_START">Перерыв</button><button class="btn" data-clock="END">Закончить</button>':'<button class="btn alt" data-clock="BREAK_END">Вернуться</button><button class="btn" data-clock="END">Закончить</button>'}</div></div><div class="panel" style="margin-top:12px;padding:15px"><h2>Смены сегодня</h2>${shifts.length?shifts.map(s=>`<div class="shift-row"><b>${esc(s.start||'')}–${esc(s.end||'')}</b> · ${esc(s.area||s.role||'')} <span class="badge">${hours(s.plannedHours)} ч</span></div>`).join(''):'<div class="muted">Смен нет</div>'}</div>`;$$('[data-clock]').forEach(b=>b.onclick=()=>clock(b.dataset.clock,b))}
async function geo(){return new Promise(resolve=>{if(!navigator.geolocation)return resolve({});navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy}),()=>resolve({}),{enableHighAccuracy:true,timeout:5000,maximumAge:60000})})}
function optimisticClock(action){const d=state.dashboard;if(!d)return;d.clock=d.clock||{};if(action==='START')d.clock={status:'WORKING',startedAt:new Date().toISOString(),workLogId:d.clock.workLogId||'',shiftId:d.todayShifts?.[0]?.id||''};if(action==='BREAK_START')d.clock.status='BREAK';if(action==='BREAK_END')d.clock.status='WORKING';if(action==='END')d.clock={status:'OFF',startedAt:'',workLogId:'',shiftId:''};saveSnapshot(LS.dashboard,d);renderHome()}
async function clock(action,button){const payload={idempotencyKey:uuid(),userAgent:navigator.userAgent,clientContext:ctx(),...(await geo())};const item={id:uuid(),kind:'clock',action,payload,createdAt:new Date().toISOString()};if(!navigator.onLine||!(await ensureToken())){const q=queue();q.push(item);setQueue(q);optimisticClock(action);toast('Смена сохранена на телефоне и уйдёт при появлении сети','warn');return}button.disabled=true;try{state.dashboard=await rpc('clockAction',[state.token,action,payload]);saveSnapshot(LS.dashboard,state.dashboard);renderHome();toast('Сохранено')}catch(e){const q=queue();q.push(item);setQueue(q);optimisticClock(action);toast('Ответ сервера потерян. Действие поставлено в безопасную очередь','warn')}finally{button.disabled=false}}
async function flushQueue(){if(!navigator.onLine||!state.token)return;let q=queue(),left=[];for(const item of q){try{if(item.kind==='clock'){state.dashboard=await rpc('clockAction',[state.token,item.action,item.payload]);saveSnapshot(LS.dashboard,state.dashboard)}else if(item.kind==='taskStatus'){await rpc('v19UpdateTask',[state.token,item.taskId,{status:item.status,note:item.note||''},ctx()])}}catch(e){left.push(item)}}setQueue(left);if(q.length!==left.length){try{state.tasks=await rpc('v19GetTaskBoard',[state.token,{}]);saveSnapshot(LS.tasks,state.tasks)}catch{}}}
function renderTeam(){const root=$('#teamBody');if(!state.user?.isOwner){root.innerHTML='<div class="empty">Доступ владельца</div>';return}const t=state.team;if(!t){root.innerHTML='<div class="empty">Нет сохранённого среза команды.</div>';return}$('#teamCount').textContent=t.totals?.staffCount||t.people?.length||0;root.innerHTML=(t.people||[]).map(p=>`<details class="person"><summary><div class="summary-line"><div><div class="name">${esc(p.name)}</div><div class="meta">${esc(p.role||'')} · ${p.contractStatus==='MISSING'?'<span class="badge bad">нет договора</span>':'<span class="badge ok">договор</span>'}</div></div><div class="right-metrics"><strong>${hours(p.todayHours)} ч</strong><span>сегодня · история ${hours(p.historyHours)} ч</span></div></div></summary><div class="detail"><div class="mini-grid"><div class="mini"><b>${eur(p.rate)}</b><span>ставка / час</span></div><div class="mini"><b>${hours(p.contractHoursWeek)}</b><span>договор / нед.</span></div><div class="mini"><b>${p.exceptionsCount||0}</b><span>проверки</span></div><div class="mini"><b>${p.contracts?.length||0}</b><span>договоры</span></div></div><div class="toolbar"><button class="btn sm" onclick="editRate('${esc(p.staffId)}',${num(p.rate)})">Ставка</button><button class="btn sm alt" onclick="editPerson('${esc(p.staffId)}')">Данные</button><button class="btn sm outline" onclick="openContracts('${esc(p.staffId)}')">Договор</button></div><div class="small muted">${esc(p.email||'')} ${p.phone?' · '+esc(p.phone):''}</div></div></details>`).join('')||'<div class="empty">Сотрудников нет</div>'}
function renderFinance(){const root=$('#financeBody');if(!state.user?.isOwner){root.innerHTML='<div class="empty">Доступ владельца</div>';return}const f=state.finance;if(!f){root.innerHTML='<div class="empty">Нет сохранённого финансового среза.</div>';return}const t=f.totals||{};$('#fromDate').value=f.fromDate||$('#fromDate').value;$('#toDate').value=f.toDate||$('#toDate').value;$('#financeTotals').innerHTML=[['Факт',hours(t.actualHours)+' ч'],['План',hours(t.plannedHours)+' ч'],['Начислено',eur(t.accruedEur)],['Выплачено',eur(t.paidEur)],['Остаток',eur(t.balanceEur)],['Проверки',t.exceptions||0]].map(([a,b])=>`<div class="metric"><strong>${b}</strong><span>${a}</span></div>`).join('');root.innerHTML=(f.people||[]).map(p=>`<details class="person"><summary><div class="summary-line"><div><div class="name">${esc(p.name)}</div><div class="meta">${hours(p.actualHours)} факт · ${hours(p.plannedHours)} план · ${eur(p.currentRate)}/ч</div></div><div class="right-metrics"><strong>${eur(p.balanceEur)}</strong><span>остаток · начислено ${eur(p.accruedEur)}</span></div></div></summary><div class="detail"><div class="mini-grid"><div class="mini"><b>${hours(p.actualHours)} ч</b><span>факт</span></div><div class="mini"><b>${eur(p.accruedEur)}</b><span>начислено</span></div><div class="mini"><b>${eur(p.paidEur)}</b><span>выплачено</span></div><div class="mini"><b>${eur(p.forecastEur)}</b><span>прогноз</span></div></div>${(p.exceptions||[]).map((x,i)=>`<div class="exception-row"><b>Требует проверки</b><div class="small">${esc(x.label||x.code||'')} ${esc(x.detail||'')}</div><button class="btn sm warn" onclick='reviewException(${JSON.stringify(JSON.stringify({p,x})).slice(1,-1)})'>Проверить</button></div>`).join('')}<div class="toolbar"><button class="btn sm" onclick="recordPayment('${esc(p.staffId)}','${esc(p.name)}')">Записать выплату</button></div>${(p.payments||[]).length?'<div class="small muted">Выплаты</div>'+p.payments.slice(0,6).map(x=>`<div class="payment-row">${esc(x.date)} · <b>${eur(x.amountEur)}</b> ${esc(x.note||'')}</div>`).join(''):''}${(p.shifts||[]).length?'<div class="small muted" style="margin-top:10px">Будущие смены</div>'+p.shifts.slice(0,10).map(s=>`<div class="shift-row">${esc(s.date)} ${esc(s.start)}–${esc(s.end)} · ${hours(s.hours)} ч · ${eur(s.forecastEur)}</div>`).join(''):''}</div></details>`).join('')}
function renderTasks(){const root=$('#tasksBody');const b=state.tasks;if(!b){root.innerHTML='<div class="empty">Нет сохранённого списка задач.</div>';return}$('#taskCount').textContent=b.counts?.open||0;$('#newTask').classList.toggle('hidden',!b.canCreate);root.innerHTML=(b.tasks||[]).map(t=>`<details class="task ${t.status==='DONE'?'done':(t.dueDate&&t.dueDate<today()&&t.status!=='DONE'?'overdue':'open')}"><summary><div class="summary-line"><div><div class="name">${esc(t.title)}</div><div class="meta">${esc(t.assigneeName||'')} · ${esc(t.dueDate||'без срока')} ${esc(t.dueTime||'')}</div></div><div class="right-metrics"><strong class="task-status">${esc(t.status)}</strong><span>${esc(t.priority)}</span></div></div></summary><div class="detail"><div>${esc(t.description||t.sourceText||'')}</div><div class="toolbar">${t.approvalStatus==='PENDING'&&b.canApprove?`<button class="btn sm" onclick="approveTask('${esc(t.id)}','APPROVE')">Подтвердить</button><button class="btn sm danger" onclick="approveTask('${esc(t.id)}','REJECT')">Отклонить</button>`:''}${t.status!=='DONE'&&t.approvalStatus==='APPROVED'?`<button class="btn sm alt" onclick="setTaskStatus('${esc(t.id)}','IN_PROGRESS')">В работу</button><button class="btn sm" onclick="setTaskStatus('${esc(t.id)}','DONE')">Готово</button>`:''}</div>${t.calendarLinked?'<span class="badge blue">в календаре</span>':''}</div></details>`).join('')||'<div class="empty">Задач нет</div>'}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden');$('#modalBody').innerHTML=''}
window.editRate=function(id,current){modal(`<h3>Ставка</h3><div class="field"><label>€/час</label><input id="mRate" inputmode="decimal" value="${num(current)}"></div><div class="field"><label>Действует с</label><input id="mDate" type="date" value="${today()}"></div><div class="footer-actions"><button class="btn alt" onclick="closeModal()">Отмена</button><button class="btn" onclick="saveRate('${esc(id)}')">Сохранить</button></div>`)};
window.saveRate=async function(id){if(!navigator.onLine)return toast('Изменение ставки требует интернет','warn');try{await rpc('v18SetHourlyRate',[state.token,{staffId:id,hourlyRate:Number($('#mRate').value),effectiveFrom:$('#mDate').value},ctx()]);closeModal();await syncAll(true);toast('Ставка сохранена')}catch(e){toast(e.message,'error')}};
window.editPerson=function(id){const p=state.team?.people?.find(x=>x.staffId===id);if(!p)return;modal(`<h3>${esc(p.name)}</h3><div class="field"><label>Email</label><input id="mEmail" value="${esc(p.email||'')}"></div><div class="field"><label>Телефон</label><input id="mPhone" value="${esc(p.phone||'')}"></div><div class="field"><label>Часы по договору / нед.</label><input id="mContract" inputmode="decimal" value="${num(p.contractHoursWeek)}"></div><div class="footer-actions"><button class="btn alt" onclick="closeModal()">Отмена</button><button class="btn" onclick="savePerson('${esc(id)}')">Сохранить</button></div>`)};
window.savePerson=async function(id){if(!navigator.onLine)return toast('Сохранение данных требует интернет','warn');try{await rpc('v200UpdateStaffProfile',[state.token,id,{email:$('#mEmail').value,phone:$('#mPhone').value,contractHoursWeek:$('#mContract').value},ctx()]);closeModal();await syncAll(true);toast('Сотрудник сохранён')}catch(e){toast(e.message,'error')}};
window.openContracts=function(id){const p=state.team?.people?.find(x=>x.staffId===id);if(!p)return;modal(`<h3>Договор · ${esc(p.name)}</h3>${(p.contracts||[]).length?(p.contracts||[]).map(c=>`<div class="payment-row"><b>${esc(c.fileName||'Договор')}</b><div class="small">${esc(c.status||'')}</div>${c.downloadUrl?`<a class="btn sm outline" href="${esc(c.downloadUrl)}" target="_blank">Открыть</a>`:''}</div>`).join(''):'<div class="empty">Договор не загружен</div>'}<div class="field"><label>Загрузить файл до 5 МБ</label><input id="contractFile" type="file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png"></div><div class="footer-actions"><button class="btn alt" onclick="closeModal()">Закрыть</button><button class="btn" onclick="uploadContract('${esc(id)}')">Загрузить</button></div>`)};
window.uploadContract=async function(id){if(!navigator.onLine)return toast('Загрузка договора требует интернет','warn');const f=$('#contractFile').files[0];if(!f)return toast('Выберите файл','warn');if(f.size>5*1024*1024)return toast('Максимум 5 МБ','warn');const base64=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]);r.onerror=rej;r.readAsDataURL(f)});try{await rpc('v18UploadContract',[state.token,{staffId:id,fileName:f.name,mimeType:f.type||'application/octet-stream',base64},ctx()]);closeModal();await syncAll(true);toast('Договор загружен')}catch(e){toast(e.message,'error')}};
window.recordPayment=function(id,name){modal(`<h3>Выплата · ${esc(name)}</h3><div class="field"><label>Сумма €</label><input id="mPay" inputmode="decimal"></div><div class="field"><label>Комментарий</label><input id="mNote" placeholder="наличные / перевод / аванс"></div><div class="footer-actions"><button class="btn alt" onclick="closeModal()">Отмена</button><button class="btn" onclick="savePayment('${esc(id)}')">Записать</button></div>`)};
window.savePayment=async function(id){if(!navigator.onLine)return toast('Выплата требует подтверждённый интернет','warn');const p=financePeriod();try{await rpc('v18RecordPayment',[state.token,{staffId:id,amount:Number($('#mPay').value),amountEur:Number($('#mPay').value),paymentDate:today(),periodFrom:p.fromDate,periodTo:p.toDate,note:$('#mNote').value},ctx()]);closeModal();await loadFinance();toast('Выплата записана')}catch(e){toast(e.message,'error')}};
window.reviewException=function(raw){let o;try{o=JSON.parse(raw)}catch{return}const p=o.p,x=o.x||{};modal(`<h3>Проверка · ${esc(p.name)}</h3><div class="small muted">${esc(x.label||x.code||'Проверка')} ${esc(x.detail||'')}</div><div class="field"><label>Верные часы</label><input id="mHours" inputmode="decimal" value="${num(x.hours||x.actualHours||x.plannedHours||0)}"></div><div class="field"><label><input id="mChecked" type="checkbox" checked> Проверено</label></div><div class="field"><label>Комментарий</label><textarea id="mReviewNote"></textarea></div><div class="footer-actions"><button class="btn alt" onclick="closeModal()">Отмена</button><button class="btn" onclick='saveReview(${JSON.stringify(JSON.stringify({p,x})).slice(1,-1)})'>Сохранить и пересчитать</button></div>`)};
window.saveReview=async function(raw){if(!navigator.onLine)return toast('Проверка требует интернет','warn');let o;try{o=JSON.parse(raw)}catch{return}const x=o.x||{},p=o.p;const per=financePeriod();const hoursVal=Number($('#mHours').value||0);try{await rpc('v18SaveAttendanceReview',[state.token,{staffId:p.staffId,fromDate:per.fromDate,toDate:per.toDate,code:x.code||'REVIEW_REQUIRED',workLogId:x.workLogId||'',shiftId:x.shiftId||'',decision:$('#mChecked').checked?'CONFIRMED_OK':'DISCREPANCY',note:$('#mReviewNote').value,evidence:{correctedHours:hoursVal},correctedHours:hoursVal,includeInPayroll:$('#mChecked').checked},ctx()]);closeModal();await loadFinance();toast('Проверено и пересчитано')}catch(e){toast(e.message,'error')}};
window.approveTask=async function(id,decision){if(!navigator.onLine)return toast('Подтверждение задачи требует интернет','warn');try{await rpc('v19ApproveTask',[state.token,id,decision,'',ctx()]);await refreshTasks();toast('Задача обновлена')}catch(e){toast(e.message,'error')}};
window.setTaskStatus=async function(id,status){if(!navigator.onLine||!(await ensureToken())){const q=queue();q.push({id:uuid(),kind:'taskStatus',taskId:id,status,createdAt:new Date().toISOString()});setQueue(q);const t=state.tasks?.tasks?.find(x=>x.id===id);if(t)t.status=status;saveSnapshot(LS.tasks,state.tasks);renderTasks();return toast('Статус сохранён локально','warn')}try{await rpc('v19UpdateTask',[state.token,id,{status},ctx()]);await refreshTasks()}catch(e){toast(e.message,'error')}};
async function refreshTasks(){state.tasks=await rpc('v19GetTaskBoard',[state.token,{}]);saveSnapshot(LS.tasks,state.tasks);renderTasks()}
function newTask(){const team=state.tasks?.team||[];modal(`<h3>Новая задача</h3><div class="field"><label>Задача</label><input id="tTitle"></div><div class="field"><label>Ответственный</label><select id="tWho">${team.map(x=>`<option value="${esc(x.staffId)}">${esc(x.name)}</option>`).join('')}</select></div><div class="period"><div class="field"><label>Срок</label><input id="tDate" type="date" value="${today()}"></div><div class="field"><label>Время</label><input id="tTime" type="time"></div></div><div class="field"><label>Приоритет</label><select id="tPr"><option>NORMAL</option><option>HIGH</option><option>URGENT</option><option>LOW</option></select></div><div class="field"><label>Описание</label><textarea id="tDesc"></textarea></div><div class="footer-actions"><button class="btn alt" onclick="closeModal()">Отмена</button><button class="btn" onclick="saveTask()">Создать</button></div>`)}
window.saveTask=async function(){if(!navigator.onLine)return toast('Создание задачи пока требует интернет','warn');try{await rpc('v19CreateTaskFromChat',[state.token,{title:$('#tTitle').value,description:$('#tDesc').value,assigneeStaffId:$('#tWho').value,dueDate:$('#tDate').value,dueTime:$('#tTime').value,priority:$('#tPr').value,sourceChannel:'PWA'},ctx()]);closeModal();await refreshTasks();toast('Задача создана')}catch(e){toast(e.message,'error')}};
function setPeriod(kind){const t=today();let f=t,to=t;if(kind==='7'){f=addDays(t,-6)}if(kind==='30'){f=addDays(t,-29)}if(kind==='month'){f=t.slice(0,8)+'01'}if(kind==='future14'){f=t;to=addDays(t,14)}if(kind==='future30'){f=t;to=addDays(t,30)}if(kind==='all'){f='2026-07-01';to=addDays(t,30)}$('#fromDate').value=f;$('#toDate').value=to;loadFinance()}
async function init(){net();lastSync();renderQueue();$('#fromDate').value=addDays(today(),-30);$('#toDate').value=today();await loadLoginOptions();await resume();if(state.user){renderAll();if(navigator.onLine)syncAll()}else setAuthed(false);addEventListener('online',()=>{net();resume().then(()=>syncAll())});addEventListener('offline',net)}
addEventListener('DOMContentLoaded',()=>{$('#loginBtn').onclick=login;$('#syncNow').onclick=()=>syncAll(true);$('#logoutBtn').onclick=logout;$('#closeModal').onclick=closeModal;$('#newTask').onclick=newTask;$('#applyPeriod').onclick=loadFinance;$$('.tab').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$$('[data-period]').forEach(b=>b.onclick=()=>setPeriod(b.dataset.period));init()});
