(()=>{
  const V='2.3';
  const CACHE_PREFIX='aumara.pwa.v23.';
  const CAL_TTL=120000;
  const RANGE_TTL=120000;
  const baseShowTab=showTab;
  const baseSyncAll=syncAll;
  let month=new Date(new Date().getFullYear(),new Date().getMonth(),1);
  let selectedDates=new Set();
  let selectMode=false;
  let calendarData=null;
  let allData=null;
  let calendarBusy=false;
  let allBusy=false;
  let drag=false;
  let dragValue=true;
  let lastDragIso='';
  let assignment={employeeIds:new Set(),area:'Bar',role:'Bar',start:'08:30',end:'16:00',breakMinutes:0,site:'El Cid Country Club',note:'',activeTemplate:''};

  const ownRole=()=>String(state.user?.accessRole||'').toUpperCase();
  const canManage=()=>!!state.user?.isOwner||!!state.user?.isManager||['OWNER','ADMIN','MANAGER'].includes(ownRole());
  const canAdmin=()=>!!state.user?.isOwner||['OWNER','ADMIN'].includes(ownRole());
  const isoDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const firstMonth=d=>new Date(d.getFullYear(),d.getMonth(),1);
  const longDate=iso=>{const p=String(iso||'').split('-').map(Number);if(p.length<3)return String(iso||'');return new Date(p[0],p[1]-1,p[2]).toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long'})};
  const shortName=n=>String(n||'').trim().split(/\s+/)[0]||'';
  const localKey=k=>CACHE_PREFIX+k;
  function cached(k){try{const x=JSON.parse(localStorage.getItem(localKey(k))||'null');return x||null}catch{return null}}
  function cache(k,data){try{localStorage.setItem(localKey(k),JSON.stringify({savedAt:new Date().toISOString(),data}))}catch{}}
  function cacheFresh(k,ttl){const x=cached(k);return !!(x?.savedAt&&Date.now()-new Date(x.savedAt).getTime()<ttl)}
  function monthKey(){return `calendar.${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}`}
  function monthCells(){const first=firstMonth(month),offset=(first.getDay()+6)%7,start=new Date(first);start.setDate(first.getDate()-offset);return Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})}
  function monthRange(){const c=monthCells();return{from:isoDate(c[0]),to:isoDate(c[c.length-1])}}
  function areaClass(area){const a=String(area||'').toLowerCase();if(a.includes('bar'))return'bar';if(a.includes('kitchen'))return'kitchen';if(a.includes('house'))return'housekeeping';if(a.includes('front'))return'front';if(a.includes('maint'))return'maintenance';if(a.includes('ground')||a.includes('plant'))return'grounds';return'other'}
  function areaLabel(s){return String(s.area||s.role||'Смена')}
  function shiftStatus(s){return String(s.status||'Published')}
  function staffList(){return state.dashboard?.manager?.staff||state.team?.people||state.dashboard?.manager?.allStaff||[]}
  function teamShifts(data){return (data?.teamShifts||[]).filter(s=>String(s.status||'')!=='Cancelled')}
  function pendingRequests(data){return data?.pendingRequests||[]}
  function fmtSync(k){const x=cached(k);return x?.savedAt?`срез ${new Date(x.savedAt).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}`:'нет локального среза'}
  function ctx23(){return {...ctx(),pwaVersion:'2.3.0',ui:'VISUAL_CALENDAR'}}

  function injectStyles(){if(document.getElementById('v23Styles'))return;const st=document.createElement('style');st.id='v23Styles';st.textContent=`
    .v23-calendar-wrap{background:#fffdf8;border:1px solid #dfd4bf;border-radius:20px;padding:8px;overflow:hidden;box-shadow:0 8px 24px #473b2810}
    .v23-cal-head{display:grid;grid-template-columns:44px minmax(0,1fr) 44px;align-items:center;gap:7px;margin-bottom:7px}.v23-month{text-align:center;font-size:18px;font-weight:950;text-transform:capitalize}.v23-icon{border:0;background:#ece2d0;color:#285746;width:44px;height:42px;border-radius:13px;font-size:25px;font-weight:900}
    .v23-weekdays,.v23-grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:4px}.v23-weekday{text-align:center;font-size:10px;font-weight:900;color:#768078;padding:5px 0}.v23-day{min-height:80px;border:1px solid #e8dfcf;border-radius:10px;background:#fffdf8;padding:4px;overflow:hidden;position:relative;user-select:none;-webkit-user-select:none}.v23-day.out{opacity:.38}.v23-day.today{box-shadow:inset 0 0 0 2px #c7a15c}.v23-day.selected{background:#e6f4ea;box-shadow:inset 0 0 0 2px #2f8b52}.v23-day.selecting{touch-action:none}.v23-day-num{font-size:12px;font-weight:950;margin-bottom:3px}.v23-day-count{position:absolute;right:4px;top:4px;font-size:9px;font-weight:900;color:#6d766f}.v23-shifts{display:grid;gap:2px}.v23-chip{border:0;border-radius:6px;padding:3px 4px;text-align:left;font-size:8.5px;font-weight:850;line-height:1.14;white-space:normal;overflow:hidden;color:#fff;background:#6c7a86}.v23-chip.bar{background:#2d6fa3}.v23-chip.kitchen{background:#d88322}.v23-chip.housekeeping{background:#7757a6}.v23-chip.front{background:#2f9d57}.v23-chip.maintenance{background:#8a6539}.v23-chip.grounds{background:#4b7b43}.v23-more{font-size:9px;color:#707a75;font-weight:850}
    .v23-quick{display:flex;gap:6px;overflow:auto;padding:8px 0 3px;scrollbar-width:none}.v23-quick::-webkit-scrollbar{display:none}.v23-q{border:0;background:#ece2d0;color:#285746;border-radius:999px;padding:9px 11px;font-size:11px;font-weight:900;white-space:nowrap}.v23-q.active{background:#285746;color:#fff}.v23-selectbar{display:flex;justify-content:space-between;align-items:center;gap:8px;background:#e7f2ea;border:1px solid #b9d8c2;border-radius:14px;padding:10px;margin-top:8px}.v23-selectbar strong{color:#176336;font-size:13px}.v23-assign{margin-top:10px;background:#fffdf8;border:1px solid #dfd4bf;border-radius:18px;padding:12px}.v23-assign>summary{font-size:16px;font-weight:950;cursor:pointer;list-style:none}.v23-assign>summary::-webkit-details-marker{display:none}.v23-employee-picker{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin-top:10px}.v23-emp{display:flex;align-items:center;gap:7px;border:1px solid #dfd4bf;background:#fffdf8;border-radius:12px;padding:9px;min-height:44px}.v23-emp:has(input:checked){background:#e7f2ea;border-color:#82b995}.v23-emp input{width:19px;height:19px;accent-color:#285746}.v23-emp span{font-size:12px;font-weight:850;line-height:1.18}.v23-template-row{display:flex;gap:7px;overflow:auto;margin:9px 0 2px;scrollbar-width:none}.v23-template-row::-webkit-scrollbar{display:none}.v23-template{border:1px solid #dfd4bf;background:#fffdf8;color:#285746;border-radius:999px;padding:9px 11px;font-size:11px;font-weight:900;white-space:nowrap}.v23-template.active{background:#285746;color:#fff}.v23-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.v23-roster{display:grid;gap:8px}.v23-roster-row{border:1px solid #dfd4bf;border-radius:13px;padding:10px;background:#fffdf8}.v23-roster-time{font-size:16px;font-weight:950}.v23-roster-meta{font-size:12px;color:#707a75;margin-top:3px}.v23-list-day{margin:13px 3px 6px;font-size:14px;font-weight:950;color:#285746}.v23-shift-card{background:#fffdf8;border:1px solid #dfd4bf;border-radius:15px;padding:11px;margin:7px 0}.v23-shift-main{display:flex;justify-content:space-between;gap:8px}.v23-shift-time{font-weight:950}.v23-shift-meta{font-size:12px;color:#707a75;margin-top:3px}.v23-shift-color{width:7px;border-radius:999px;background:#6c7a86;flex:0 0 7px}.v23-shift-color.bar{background:#2d6fa3}.v23-shift-color.kitchen{background:#d88322}.v23-shift-color.housekeeping{background:#7757a6}.v23-shift-color.front{background:#2f9d57}.v23-shift-color.maintenance{background:#8a6539}.v23-shift-color.grounds{background:#4b7b43}.v23-request{background:#fffdf8;border:1px solid #dfd4bf;border-radius:15px;padding:12px;margin:8px 0}.v23-request strong{display:block}.v23-request-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}
    @media(max-width:520px){.v23-calendar-wrap{padding:5px}.v23-weekdays,.v23-grid{gap:3px}.v23-day{min-height:73px;padding:3px}.v23-chip{font-size:7.7px;padding:3px}.v23-day-num{font-size:11px}.v23-employee-picker{grid-template-columns:1fr}.v23-form-grid{grid-template-columns:1fr 1fr}}
  `;document.head.appendChild(st)}

  function ensureSection(name,title,note){const main=document.querySelector('#app .main');let sec=document.getElementById('sec-'+name);if(!sec){sec=document.createElement('section');sec.id='sec-'+name;sec.className='section hidden';main.appendChild(sec)}sec.innerHTML=`<div class="section-head"><h2>${title}</h2><span class="syncnote" id="${name}Note">${note||''}</span></div><div id="${name}Body"></div>`;return sec}
  function tab(name,label){const nav=document.querySelector('#app .tabs');let b=nav.querySelector(`[data-tab="${name}"]`);if(!b){b=document.createElement('button');b.className='tab';b.dataset.tab=name;b.textContent=label;b.onclick=()=>showTab(name)}else b.textContent=label;return b}
  function reorderTabs(){const nav=document.querySelector('#app .tabs');if(!nav)return;const order=['home','schedule','all','calendar','chat','requests'];order.forEach(n=>{const b=nav.querySelector(`[data-tab="${n}"]`);if(b)nav.appendChild(b)});const owner=document.getElementById('ownerTabs');if(owner)nav.appendChild(owner);['tasks','audit','devices'].forEach(n=>{const b=nav.querySelector(`[data-tab="${n}"]`);if(b)nav.appendChild(b)})}
  function ensureUi(){
    injectStyles();
    const nav=document.querySelector('#app .tabs');if(!nav)return;
    tab('schedule','Мой график');tab('all','Все смены');tab('calendar','Календарь');tab('requests','Запросы');
    ensureSection('schedule','Мой график','личное расписание');
    ensureSection('all','Все смены','команда · 35 дней');
    ensureSection('calendar','Календарь','месяц · выберите дни пальцем');
    ensureSection('requests','Запросы','изменения и отгулы');
    const reqTab=nav.querySelector('[data-tab="requests"]');if(reqTab)reqTab.classList.toggle('hidden',!canManage());
    reorderTabs();
    const v=document.getElementById('version');if(v)v.textContent='PWA '+V;
    ensureRequestButton();
  }

  function activate(name){state.active=name;document.querySelectorAll('.tab[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.section').forEach(s=>s.classList.add('hidden'));document.getElementById('sec-'+name)?.classList.remove('hidden')}
  showTab=async function(name){ensureUi();if(name==='calendar'){activate(name);await loadCalendar(false);return}if(name==='schedule'){activate(name);renderSchedule();return}if(name==='all'){activate(name);await loadAll(false);return}if(name==='requests'){activate(name);await loadAll(false);renderRequests();return}return baseShowTab(name)};
  syncAll=async function(force=false){const active=state.active;if(active==='calendar')state.active='home';const r=await baseSyncAll(force);state.active=active;ensureUi();if(active==='calendar'){activate('calendar');await loadCalendar(true)}else if(active==='schedule'){activate('schedule');renderSchedule()}else if(active==='all'){activate('all');await loadAll(true)}else if(active==='requests'){activate('requests');await loadAll(true);renderRequests()}return r};

  async function loadCalendar(force){
    ensureUi();const k=monthKey(),c=cached(k);if(c?.data){calendarData=c.data;renderCalendar()}else renderCalendar();
    if(!navigator.onLine||calendarBusy)return;if(!force&&cacheFresh(k,CAL_TTL))return;if(!(await ensureToken()))return;
    calendarBusy=true;const note=document.getElementById('calendarNote');if(note)note.textContent='обновляю…';
    try{const r=monthRange();calendarData=await rpc('getManagerCalendar',[state.token,r.from,r.to]);cache(k,calendarData);renderCalendar()}catch(e){toast('Календарь: '+e.message,'error')}finally{calendarBusy=false;const n=document.getElementById('calendarNote');if(n)n.textContent='месяц · '+fmtSync(k)}
  }
  function defaultsTemplates(){return[
    {id:'morning',label:'Утро 08:30–16:00',area:'Bar',role:'Bar',start:'08:30',end:'16:00',breakMinutes:0},
    {id:'day',label:'День 10:00–18:00',area:'Other',role:'Shift',start:'10:00',end:'18:00',breakMinutes:0},
    {id:'evening',label:'Вечер 16:00–00:00',area:'Bar',role:'Bar',start:'16:00',end:'00:00',breakMinutes:0},
    {id:'kitchen',label:'Kitchen 10:00–18:00',area:'Kitchen',role:'Kitchen',start:'10:00',end:'18:00',breakMinutes:0}
  ]}
  function templates(){const arr=state.dashboard?.manager?.templates;return Array.isArray(arr)&&arr.length?arr:defaultsTemplates()}
  function renderCalendar(){
    const root=document.getElementById('calendarBody');if(!root)return;const data=calendarData||cached(monthKey())?.data||{};const shifts=teamShifts(data);const cells=monthCells();const by={};shifts.forEach(s=>(by[s.date]||(by[s.date]=[])).push(s));const title=month.toLocaleDateString('ru-RU',{month:'long',year:'numeric'});const manager=canManage();
    root.innerHTML=`<div class="v23-calendar-wrap"><div class="v23-cal-head"><button class="v23-icon" id="v23Prev">‹</button><div class="v23-month">${esc(title)}</div><button class="v23-icon" id="v23Next">›</button></div><div class="v23-weekdays">${['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=>`<div class="v23-weekday">${x}</div>`).join('')}</div><div class="v23-grid" id="v23Grid">${cells.map(d=>{const iso=isoDate(d),list=(by[iso]||[]).sort((a,b)=>String(a.start).localeCompare(String(b.start))),out=d.getMonth()!==month.getMonth(),sel=selectedDates.has(iso),shown=list.slice(0,5);return`<div class="v23-day ${out?'out':''} ${iso===today()?'today':''} ${sel?'selected':''} ${selectMode?'selecting':''}" data-iso="${iso}"><div class="v23-day-num">${d.getDate()}</div>${list.length?`<div class="v23-day-count">${list.length}</div>`:''}<div class="v23-shifts">${shown.map(s=>`<button type="button" class="v23-chip ${areaClass(areaLabel(s))}" data-shift="${esc(s.id||'')}">${esc(s.start||'')} ${esc(shortName(s.employee))}</button>`).join('')}${list.length>5?`<div class="v23-more">+${list.length-5}</div>`:''}</div></div>`}).join('')}</div></div>
    ${manager?`<div class="v23-quick"><button class="v23-q ${selectMode?'active':''}" id="v23SelectMode">${selectMode?'Готово':'Выбрать дни'}</button><button class="v23-q" data-pick="weekdays">Пн–Пт</button><button class="v23-q" data-pick="weekend">Сб–Вс</button><button class="v23-q" data-pick="month">Весь месяц</button><button class="v23-q" data-pick="clear">Очистить</button><button class="v23-q" data-pick="today">Сегодня</button></div><div class="v23-selectbar"><strong id="v23Selection">${selectionText()}</strong><button class="btn sm alt" data-pick="clear">Сбросить</button></div>${assignmentPanel()}`:''}`;
    bindCalendar(shifts);
  }
  function selectionText(){const d=selectedDates.size,e=assignment.employeeIds.size,total=d*e;if(!d)return'Выберите дни пальцем';if(!e)return`Дней: ${d} · выберите сотрудников`;return`Дней: ${d} · сотрудников: ${e} · смен: ${total}`}
  function assignmentPanel(){const people=staffList(),ts=templates();return`<details class="v23-assign" id="v23Assign" ${selectedDates.size?'open':''}><summary>Назначение смен · ${selectedDates.size?selectedDates.size+' дн.':'выберите дни'}</summary><div class="v23-employee-picker">${people.map(p=>`<label class="v23-emp"><input type="checkbox" data-emp="${esc(p.staffId)}" ${assignment.employeeIds.has(p.staffId)?'checked':''}><span>${esc(p.name)}<br><small>${esc(p.role||'')}</small></span></label>`).join('')}</div><div class="toolbar"><button class="btn sm alt" id="v23EmpAll">Выбрать всех</button><button class="btn sm outline" id="v23EmpClear">Очистить</button></div><div class="v23-template-row">${ts.map(t=>`<button class="v23-template ${assignment.activeTemplate===t.id?'active':''}" data-template="${esc(t.id||'')}">${esc(t.label||t.name||t.id||'Шаблон')}</button>`).join('')}</div><div class="v23-form-grid"><div class="field"><label>Работа / зона</label><select id="v23Area">${['Bar','Kitchen','Housekeeping','Front Desk','Maintenance','Grounds / Plants','Other'].map(a=>`<option ${assignment.area===a?'selected':''}>${a}</option>`).join('')}</select></div><div class="field"><label>Название смены</label><input id="v23Role" value="${esc(assignment.role)}"></div><div class="field"><label>Начало</label><input id="v23Start" type="time" value="${esc(assignment.start)}"></div><div class="field"><label>Конец</label><input id="v23End" type="time" value="${esc(assignment.end)}"></div><div class="field"><label>Перерыв, мин</label><input id="v23Break" type="number" min="0" value="${Number(assignment.breakMinutes||0)}"></div><div class="field"><label>Объект</label><input id="v23Site" value="${esc(assignment.site)}"></div></div><div class="field"><label>Комментарий</label><input id="v23Note" value="${esc(assignment.note)}" placeholder="Необязательно"></div><button class="btn" id="v23Batch">${selectedDates.size&&assignment.employeeIds.size?`Назначить смены: ${selectedDates.size*assignment.employeeIds.size}`:'Назначить смены'}</button></details>`}
  function bindCalendar(shifts){
    document.getElementById('v23Prev')?.addEventListener('click',()=>moveMonth(-1));document.getElementById('v23Next')?.addEventListener('click',()=>moveMonth(1));document.getElementById('v23SelectMode')?.addEventListener('click',()=>{selectMode=!selectMode;renderCalendar()});
    document.querySelectorAll('[data-pick]').forEach(b=>b.addEventListener('click',()=>quickPick(b.dataset.pick)));
    const grid=document.getElementById('v23Grid');if(grid){grid.addEventListener('click',e=>{const chip=e.target.closest('.v23-chip');if(chip){e.stopPropagation();const s=shifts.find(x=>String(x.id||'')===chip.dataset.shift);return openShift(s)}const cell=e.target.closest('.v23-day');if(!cell)return;const iso=cell.dataset.iso;if(canManage()&&selectMode)toggleDay(iso);else openRoster(iso,shifts)});grid.addEventListener('pointerdown',e=>{if(!canManage()||!selectMode)return;const cell=e.target.closest('.v23-day');if(!cell)return;e.preventDefault();drag=true;lastDragIso=cell.dataset.iso;dragValue=!selectedDates.has(lastDragIso);setDay(lastDragIso,dragValue)});grid.addEventListener('pointermove',e=>{if(!drag||!selectMode)return;const el=document.elementFromPoint(e.clientX,e.clientY)?.closest?.('.v23-day');if(!el||!grid.contains(el)||el.dataset.iso===lastDragIso)return;e.preventDefault();lastDragIso=el.dataset.iso;setDay(lastDragIso,dragValue)});['pointerup','pointercancel','pointerleave'].forEach(ev=>grid.addEventListener(ev,()=>{drag=false;lastDragIso=''}))}
    document.querySelectorAll('[data-emp]').forEach(c=>c.addEventListener('change',()=>{c.checked?assignment.employeeIds.add(c.dataset.emp):assignment.employeeIds.delete(c.dataset.emp);updateSelectionUi()}));document.getElementById('v23EmpAll')?.addEventListener('click',()=>{staffList().forEach(p=>assignment.employeeIds.add(p.staffId));renderCalendar()});document.getElementById('v23EmpClear')?.addEventListener('click',()=>{assignment.employeeIds.clear();renderCalendar()});
    document.querySelectorAll('[data-template]').forEach(b=>b.addEventListener('click',()=>applyTemplate(b.dataset.template)));[['v23Area','area'],['v23Role','role'],['v23Start','start'],['v23End','end'],['v23Site','site'],['v23Note','note']].forEach(([id,k])=>document.getElementById(id)?.addEventListener('input',e=>assignment[k]=e.target.value));document.getElementById('v23Break')?.addEventListener('input',e=>assignment.breakMinutes=Number(e.target.value||0));document.getElementById('v23Batch')?.addEventListener('click',createBatch);
  }
  function updateSelectionUi(){const n=document.getElementById('v23Selection');if(n)n.textContent=selectionText();const b=document.getElementById('v23Batch');if(b)b.textContent=selectedDates.size&&assignment.employeeIds.size?`Назначить смены: ${selectedDates.size*assignment.employeeIds.size}`:'Назначить смены'}
  function setDay(iso,on){on?selectedDates.add(iso):selectedDates.delete(iso);const cell=document.querySelector(`.v23-day[data-iso="${iso}"]`);cell?.classList.toggle('selected',on);updateSelectionUi();const d=document.getElementById('v23Assign');if(d&&selectedDates.size)d.open=true}
  function toggleDay(iso){setDay(iso,!selectedDates.has(iso))}
  function quickPick(kind){if(kind==='today'){month=firstMonth(new Date());selectedDates.clear();selectMode=false;return loadCalendar(true)}selectMode=true;selectedDates.clear();const y=month.getFullYear(),m=month.getMonth(),last=new Date(y,m+1,0).getDate();if(kind==='weekdays'||kind==='weekend'||kind==='month'){for(let i=1;i<=last;i++){const d=new Date(y,m,i),dow=d.getDay();if(kind==='month'||(kind==='weekdays'&&dow>=1&&dow<=5)||(kind==='weekend'&&(dow===0||dow===6)))selectedDates.add(isoDate(d))}}if(kind==='clear')selectedDates.clear();renderCalendar()}
  function applyTemplate(id){const t=templates().find(x=>String(x.id||'')===String(id));if(!t)return;assignment.activeTemplate=id;if(!t.timeOnly){assignment.area=t.area||assignment.area;assignment.role=t.role||t.name||assignment.role}assignment.start=t.start||assignment.start;assignment.end=t.end||assignment.end;assignment.breakMinutes=Number(t.breakMinutes||0);renderCalendar()}
  async function moveMonth(delta){month=new Date(month.getFullYear(),month.getMonth()+delta,1);selectedDates.clear();selectMode=false;calendarData=null;await loadCalendar(false)}
  async function createBatch(){if(!navigator.onLine)return toast('Назначение смен требует интернет','warn');if(!selectedDates.size)return toast('Сначала выберите дни в календаре','warn');if(!assignment.employeeIds.size)return toast('Выберите хотя бы одного сотрудника','warn');if(!(await ensureToken()))return;const button=document.getElementById('v23Batch');if(button)button.disabled=true;try{const input={dates:[...selectedDates].sort(),employeeStaffIds:[...assignment.employeeIds],area:assignment.area,role:assignment.role,start:assignment.start,end:assignment.end,breakMinutes:Number(assignment.breakMinutes||0),site:assignment.site,note:assignment.note,publish:true};const r=await rpc('createShiftsBatch',[state.token,input,ctx23()]);selectedDates.clear();selectMode=false;calendarData=null;await loadCalendar(true);try{state.dashboard=r?.dashboard||await rpc('getDashboard',[state.token]);saveSnapshot(LS.dashboard,state.dashboard)}catch{}toast(`Назначено смен: ${r?.created?.length??input.dates.length*input.employeeStaffIds.length}`)}catch(e){toast(e.message,'error')}finally{if(button)button.disabled=false}}

  function openRoster(iso,shifts){const rows=shifts.filter(s=>s.date===iso).sort((a,b)=>String(a.start).localeCompare(String(b.start)));modal(`<h3>${esc(longDate(iso))}</h3><div class="v23-roster">${rows.length?rows.map(s=>`<div class="v23-roster-row"><div class="v23-roster-time">${esc(s.start||'')}–${esc(s.end||'')} · ${esc(s.employee||'')}</div><div class="v23-roster-meta">${esc(areaLabel(s))} · ${esc(s.site||'')} · ${esc(shiftStatus(s))}</div>${canManage()?`<button class="btn sm outline" data-roster-edit="${esc(s.id||'')}" style="margin-top:8px">Изменить</button>`:''}</div>`).join(''):'<div class="empty">Никто не назначен.</div>'}</div>${canManage()?'<div class="footer-actions"><button class="btn" id="v23PickRosterDay">Выбрать этот день для назначения</button></div>':''}`);document.querySelectorAll('[data-roster-edit]').forEach(b=>b.onclick=()=>{closeModal();openShift(rows.find(s=>String(s.id||'')===b.dataset.rosterEdit))});document.getElementById('v23PickRosterDay')?.addEventListener('click',()=>{selectMode=true;selectedDates.add(iso);closeModal();renderCalendar()})}
  function employeeOptions(selected){return staffList().map(p=>`<option value="${esc(p.staffId)}" ${p.staffId===selected?'selected':''}>${esc(p.name)} — ${esc(p.role||'')}</option>`).join('')}
  function openShift(s){if(!s)return;if(!canManage()){modal(`<h3>${esc(s.employee||'Смена')}</h3><p><b>${esc(longDate(s.date))} · ${esc(s.start)}–${esc(s.end)}</b></p><p>${esc(areaLabel(s))} · ${esc(s.site||'')}</p><p class="muted">${esc(s.note||'')}</p>`);return}modal(`<h3>Изменить смену</h3><div class="field"><label>Дата</label><input id="v23eDate" type="date" value="${esc(s.date||'')}"></div><div class="field"><label>Сотрудник</label><select id="v23eStaff">${employeeOptions(s.employeeStaffId)}</select></div><div class="v23-form-grid"><div class="field"><label>Зона</label><select id="v23eArea">${['Bar','Kitchen','Housekeeping','Front Desk','Maintenance','Grounds / Plants','Other'].map(a=>`<option ${areaLabel(s)===a?'selected':''}>${a}</option>`).join('')}</select></div><div class="field"><label>Название</label><input id="v23eRole" value="${esc(s.role||areaLabel(s))}"></div><div class="field"><label>Начало</label><input id="v23eStart" type="time" value="${esc(s.start||'')}"></div><div class="field"><label>Конец</label><input id="v23eEnd" type="time" value="${esc(s.end||'')}"></div><div class="field"><label>Перерыв, мин</label><input id="v23eBreak" type="number" value="${Number(s.breakMinutes||0)}"></div><div class="field"><label>Статус</label><select id="v23eStatus"><option ${shiftStatus(s)==='Published'?'selected':''}>Published</option><option ${shiftStatus(s)==='Draft'?'selected':''}>Draft</option></select></div></div><div class="field"><label>Комментарий</label><textarea id="v23eNote">${esc(s.note||'')}</textarea></div><div class="footer-actions"><button class="btn danger" id="v23CancelShift">Отменить смену</button><button class="btn" id="v23SaveShift">Сохранить</button></div>`);document.getElementById('v23SaveShift').onclick=()=>saveShift(s.id);document.getElementById('v23CancelShift').onclick=()=>cancelShift(s.id)}
  async function saveShift(id){if(!navigator.onLine)return toast('Изменение смены требует интернет','warn');try{await rpc('updateShift',[state.token,id,{date:document.getElementById('v23eDate').value,employeeStaffId:document.getElementById('v23eStaff').value,area:document.getElementById('v23eArea').value,role:document.getElementById('v23eRole').value,start:document.getElementById('v23eStart').value,end:document.getElementById('v23eEnd').value,breakMinutes:Number(document.getElementById('v23eBreak').value||0),status:document.getElementById('v23eStatus').value,note:document.getElementById('v23eNote').value},ctx23()]);closeModal();calendarData=null;await loadCalendar(true);toast('Смена обновлена')}catch(e){toast(e.message,'error')}}
  async function cancelShift(id){if(!navigator.onLine)return toast('Отмена смены требует интернет','warn');try{await rpc('setShiftStatus',[state.token,id,'Cancelled',ctx23()]);closeModal();calendarData=null;await loadCalendar(true);toast('Смена отменена')}catch(e){toast(e.message,'error')}}

  function shiftCard(s,phone=false){return`<div class="v23-shift-card"><div class="v23-shift-main"><div class="v23-shift-color ${areaClass(areaLabel(s))}"></div><div class="grow"><div class="v23-shift-time">${esc(s.start||'')}–${esc(s.end||'')} · ${esc(s.employee||state.user?.name||'')}</div><div class="v23-shift-meta">${esc(areaLabel(s))} · ${esc(s.site||'')} ${shiftStatus(s)==='Draft'?'· черновик':''}</div></div>${phone?`<button class="btn sm outline" data-ics="${esc(s.id||'')}">В телефон</button>`:''}</div></div>`}
  function renderSchedule(){ensureUi();const root=document.getElementById('scheduleBody');if(!root)return;const shifts=(state.dashboard?.upcomingShifts||[]).filter(s=>String(s.date||'')>=today()).sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start)),by={};shifts.forEach(s=>(by[s.date]||(by[s.date]=[])).push(s));root.innerHTML=Object.keys(by).length?Object.keys(by).sort().map(d=>`<div class="v23-list-day">${esc(longDate(d))}</div>${by[d].map(s=>shiftCard(s,true)).join('')}`).join(''):'<div class="empty">Предстоящих смен нет.</div>';root.querySelectorAll('[data-ics]').forEach(b=>b.onclick=()=>shareIcs(shifts.find(s=>String(s.id||'')===b.dataset.ics)))}
  function icsDateTime(date,time,addDay=0){const p=date.split('-').map(Number),tm=time.split(':').map(Number),d=new Date(p[0],p[1]-1,p[2]+addDay,tm[0],tm[1]);return`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}T${String(d.getHours()).padStart(2,'0')}${String(d.getMinutes()).padStart(2,'0')}00`}
  function buildIcs(s){const e=v=>String(v||'').replace(/([,;\\])/g,'\\$1').replace(/\n/g,'\\n'),start=icsDateTime(s.date,s.start),end=icsDateTime(s.date,s.end,s.end<=s.start?1:0);return['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//AUMARA//Staff Shift//RU','CALSCALE:GREGORIAN','BEGIN:VEVENT',`UID:${e(s.id)}@aumara`,`DTSTART;TZID=Europe/Madrid:${start}`,`DTEND;TZID=Europe/Madrid:${end}`,`SUMMARY:${e('AUMARA · '+areaLabel(s))}`,`LOCATION:${e(s.site||'')}`,`DESCRIPTION:${e(s.note||'AUMARA Staff')}`,'END:VEVENT','END:VCALENDAR'].join('\r\n')}
  async function shareIcs(s){if(!s)return;try{const file=new File([buildIcs(s)],`AUMARA-${s.date}-${String(s.start).replace(':','')}.ics`,{type:'text/calendar'});if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'AUMARA Staff'});else{const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}}catch(e){toast(e.message,'error')}}

  async function loadAll(force){ensureUi();const c=cached('all35');if(c?.data){allData=c.data;renderAllShifts()}else renderAllShifts();if(!navigator.onLine||allBusy)return;if(!force&&cacheFresh('all35',RANGE_TTL))return;if(!(await ensureToken()))return;allBusy=true;const note=document.getElementById('allNote');if(note)note.textContent='обновляю…';try{allData=await rpc('getManagerCalendar',[state.token,today(),addDays(today(),35)]);cache('all35',allData);renderAllShifts();if(state.active==='requests')renderRequests()}catch(e){toast('Все смены: '+e.message,'error')}finally{allBusy=false;const n=document.getElementById('allNote');if(n)n.textContent='команда · '+fmtSync('all35')}}
  function renderAllShifts(){const root=document.getElementById('allBody');if(!root)return;const shifts=teamShifts(allData||cached('all35')?.data||{}).filter(s=>String(s.date||'')>=today()).sort((a,b)=>(a.date+a.start+a.employee).localeCompare(b.date+b.start+b.employee)),by={};shifts.forEach(s=>(by[s.date]||(by[s.date]=[])).push(s));root.innerHTML=`<div class="summary-grid"><div class="metric"><strong>${shifts.length}</strong><span>назначений · 35 дней</span></div><div class="metric"><strong>${new Set(shifts.map(s=>s.employeeStaffId||s.employee)).size}</strong><span>сотрудников в графике</span></div></div>${Object.keys(by).length?Object.keys(by).sort().map(d=>`<div class="v23-list-day">${esc(longDate(d))}</div>${by[d].map(s=>shiftCard(s,false)).join('')}`).join(''):'<div class="empty">Общих смен пока нет.</div>'}`}

  function renderRequests(){const root=document.getElementById('requestsBody');if(!root)return;if(!canManage()){root.innerHTML='<div class="empty">Запросы сотрудников доступны менеджеру.</div>';return}const req=pendingRequests(allData||cached('all35')?.data||{});const tab=document.querySelector('[data-tab="requests"]');if(tab)tab.textContent=req.length?`Запросы ${req.length}`:'Запросы';root.innerHTML=req.length?req.map(r=>`<div class="v23-request"><strong>${esc(r.employee||'')} — ${esc(requestTypeLabel(r.type))}</strong><div class="small muted">${esc(r.shiftId||'Без конкретной смены')} · ${esc(r.urgency||'Normal')}</div><p>${esc(r.reason||r.requestedChange||'Без комментария')}</p><div class="v23-request-actions"><button class="btn sm" data-req="${esc(r.id)}" data-decision="Approved">Одобрить</button><button class="btn sm alt" data-req="${esc(r.id)}" data-decision="Need information">Уточнить</button><button class="btn sm danger" data-req="${esc(r.id)}" data-decision="Declined">Отклонить</button></div></div>`).join(''):'<div class="empty">Новых запросов нет.</div>';root.querySelectorAll('[data-req]').forEach(b=>b.onclick=()=>decideRequest23(b.dataset.req,b.dataset.decision))}
  function requestTypeLabel(v){return({'Cannot attend':'Не могу выйти','Shift change':'Изменить смену','Time off':'Выходной / отсутствие','Late arrival':'Опоздаю'})[v]||v||'Запрос'}
  async function decideRequest23(id,decision){if(!navigator.onLine)return toast('Решение требует интернет','warn');try{await rpc('decideRequest',[state.token,id,decision,'',ctx23()]);allData=null;await loadAll(true);renderRequests();toast('Решение сохранено')}catch(e){toast(e.message,'error')}}

  function ensureRequestButton(){const home=document.getElementById('homeBody');if(!home||document.getElementById('v23RequestBtn'))return;const b=document.createElement('button');b.id='v23RequestBtn';b.className='btn outline';b.style.marginTop='12px';b.textContent='Создать запрос менеджеру';b.onclick=openRequest;home.appendChild(b)}
  function openRequest(){const shifts=(state.dashboard?.upcomingShifts||[]).filter(s=>String(s.date||'')>=today());modal(`<h3>Новый запрос</h3><div class="field"><label>Смена</label><select id="v23rShift"><option value="">Без конкретной смены</option>${shifts.map(s=>`<option value="${esc(s.id||'')}">${esc(s.date)} ${esc(s.start)}–${esc(s.end)} ${esc(s.role||s.area||'')}</option>`).join('')}</select></div><div class="field"><label>Тип</label><select id="v23rType"><option value="Cannot attend">Не могу выйти</option><option value="Shift change">Изменить смену</option><option value="Time off">Выходной / отсутствие</option><option value="Late arrival">Опоздаю</option></select></div><div class="field"><label>Что нужно изменить</label><input id="v23rChange"></div><div class="field"><label>Причина</label><textarea id="v23rReason"></textarea></div><div class="footer-actions"><button class="btn alt" onclick="closeModal()">Отмена</button><button class="btn" id="v23rSend">Отправить</button></div>`);document.getElementById('v23rSend').onclick=submitRequest23}
  async function submitRequest23(){if(!navigator.onLine)return toast('Отправка запроса требует интернет','warn');if(!(await ensureToken()))return;try{state.dashboard=await rpc('submitRequest',[state.token,{shiftId:document.getElementById('v23rShift').value,type:document.getElementById('v23rType').value,requestedChange:document.getElementById('v23rChange').value,reason:document.getElementById('v23rReason').value,urgency:'Normal'},ctx23()]);saveSnapshot(LS.dashboard,state.dashboard);closeModal();toast('Запрос отправлен');if(canManage()){allData=null;loadAll(true)}}catch(e){toast(e.message,'error')}}

  const observer=new MutationObserver(()=>{ensureUi();if(state.active==='home')ensureRequestButton()});observer.observe(document.documentElement,{childList:true,subtree:true});
  addEventListener('online',()=>{if(state.active==='calendar')loadCalendar(true);if(state.active==='all'||state.active==='requests')loadAll(true)});
  addEventListener('DOMContentLoaded',()=>{ensureUi();setTimeout(()=>{ensureUi();if(state.active==='calendar')loadCalendar(false);if(state.active==='schedule')renderSchedule();if(state.active==='all')loadAll(false);if(state.active==='requests')loadAll(false)},80)});
})();