name: Skeet
on:
  push:
    branches:
      - main
    paths:
      - 'functions/skeet/**'
      - '.github/workflows/functions-skeet.yml'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.1'
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.SKEET_GCP_SA_KEY }}
      - name: Install yarn and firebase tools
        run: npm i -g npm yarn firebase-tools
      - name: GitHub repository setting
        run: git config --global url."https://github.com".insteadOf ssh://git@github.com
      - name: Install dependencies
        run: cd ./functions/skeet && yarn install --frozen-lockfile
      - name: Build App
        run: cd ./functions/skeet && yarn build
      - name: Deploy to Firebase
        run: firebase deploy --only functions:skeet
