name: Rebuild Cookbook Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Call Deploy Hook
        env:
          URL: ${{ secrets.WEBSITE_DEPLOY_HOOK_URL }}
        run: |
          if [ -n "$URL" ]; then
            curl -sf -X POST "$URL"
          else
            echo "WEBSITE_DEPLOY_HOOK_URL not set, skipping deploy hook."
          fi
