name: Rebuild Cookbook Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Call Deploy Hook
        run: curl -X POST ${WEBSITE_DEPLOY_HOOK_URL}
        env:
          WEBSITE_DEPLOY_HOOK_URL: ${{ secrets.WEBSITE_DEPLOY_HOOK_URL }}
