name: Generate RSS Feed

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Generate rss.xml
        run: python .github/scripts/generate_rss.py

      - name: Commit and push changes
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain rss.xml)" ]; then
            git add rss.xml
            git commit -m "chore: update RSS feed"
            # Fetch latest changes and rebase before pushing
            git fetch origin
            if ! git rebase origin/main; then
              echo "Error: git rebase origin/main failed. Please check for conflicts."
              exit 1
            fi
            # Try to push up to 3 times in case of race conditions
            n=0
            until [ $n -ge 3 ]; do
              if git push; then
                break
              fi
              n=$((n+1))
              echo "git push failed, retrying ($n/3)..."
              sleep 2
              git fetch origin
              if ! git rebase origin/main; then
                echo "Error: git rebase origin/main failed during retry. Please check for conflicts."
                exit 1
              fi
            done
            if [ $n -ge 3 ]; then
              echo "Error: git push failed after 3 attempts. Please check network or remote conflicts."
              exit 1
            fi
          else
            echo "No changes to rss.xml"
          fi

