name: Validate Changed Notebooks

on: [pull_request]

jobs:
  validate-notebooks:
    name: Validate Notebooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # needed for git diff to work

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install nbformat

      - name: Validate changed .ipynb files
        run: python .github/scripts/check_notebooks.py
