name: Validate Changed Notebooks

on: [pull_request]

jobs:
  validate-notebooks:
    name: Validate Notebooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0  # needed for git diff to work

      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install nbformat

      - name: Validate changed .ipynb files
        run: python .github/scripts/check_notebooks.py
